language: python
python:
#  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd tests
  - if [[ $TRAVIS_PYTHON_VERSION == 2* || $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then python ./test_cli.py ./cmd_list_py2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* || $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then python ./test_cli.py ./cmd_list_py3.txt; fi
